{% set name = "intel-graphics-compiler" %}
{% set version = "1.0.3032" %}
{% set llvm_version = "9.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/intel/{{ name }}/archive/igc-{{ version }}.tar.gz
  sha256: 242c90e37c899a288214aaa53b5d368d42739e3af0b2792f024db62ef3a2ed29

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - flex
    - bison
  host:
    - llvmdev   {{ llvm_version }}
    - llvm      {{ llvm_version }}
    - clangdev  {{ llvm_version }}
    - intel-opencl-clang {{ llvm_version }}
  run:
    - intel-opencl-clang {{ llvm_version }}
  run_constrained:
    - llvmdev   {{ llvm_version }}
    - clangdev  {{ llvm_version }}

test:
  commands:
    - test -f ${PREFIX}/lib/libiga64${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/intel/intel-graphics-compiler
  license: MIT
  license_file: LICENSE.md
  license_family: MIT
  summary: 'The Intel(R) Graphics Compiler for OpenCL(TM) is an llvm based compiler for OpenCL(TM) targeting Intel Gen graphics hardware architecture.'

extra:
  recipe-maintainers:
    - isuruf
