travis:
  secure:
    BINSTAR_TOKEN: EzWrl5Wz+2OEl9eiqh3ebSc9FHtmWId7Nf8io4E46F+1b8iAs1OLsYg05yTh1owLI3d2JMyFKLOYc7z1eo4+Vc3MRy8/8T0RMCP3UvF3dJQMy+2X/CRpIkcdQsUD0iXxKVHHFVNM0AuOuRzglu5+COMoNpCKCUts1yxB8ux6FFub7ghh/W75V3hMscqSdVs+2fHn+RsVHPF6BdNImRzCqdLd7OysiN1r7MKC3W7/o+QfxnjazlznJOLax8AvnkNoXMfvORyrByq9hDhGLqwORoPfTCeKoknLw/8u0VBaB76m41PFtwGnr4YPAMtjbx+BwnCiKQ0NHV9MQCrzB8KsctkIbL4hm30r8zuJBe5MfF/mDawBgNq6oJ1RP/lKOnviecPzilxKcbhyjsOQBxq/7sjFjsXG+usYcg47UuEGaWH9YgpzeedlXGUVtOcnjJUeVlKtveBQvx+sEjXg4M3hfgWGhw7Moz2KMIf+Unj003FfpIOy2U1Zkxy85senZPEYmdQp3C6nhzz7r4LYnVgEKGBG1wfhRU46ipvempFeT/IAYI4o9/iYcGxdlYrXFChE/ajixfSBq1/sGOH3akGHBOvdD/bHkcrLr2BuVIfD6iAiAjcfbIVuGvJzIQIMpv9FqbNs/FODVyKY/a1Rv0b0kfDhWt/Xloxrz9HP3HaGkMg=
bot:
  automerge: true
conda_forge_output_validation: true
